version: '3.8'

services:
  server:
    build: ./server
    ports:
      - "8000:8000"
    environment:
      SQLALCHEMY_DATABASE_URL: "postgresql://testuser:testpassword@postgres:5432/testdb"
      MONGODB_URL: "mongodb://mongo:27017/"
    depends_on:
      - postgres
      - mongo

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword

  mongo:
    image: mongo:latest

  adminer:
    image: adminer
    ports:
      - "8080:8080"